#ifndef QTAWSSIGNATUREV4_GLOBAL_H
#define QTAWSSIGNATUREV4_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTAWSSIGNATUREV4_LIBRARY)
#  define QTAWSSIGNATUREV4_EXPORT Q_DECL_EXPORT
#else
#  define QTAWSSIGNATUREV4_EXPORT Q_DECL_IMPORT
#endif

#endif // QTAWSSIGNATUREV4_GLOBAL_H
